JBDEVSTUDIO_INSTALA_OPCS='--nao-baixa-arquivo'
JBDEVSTUDIO_DIR=jbdevstudio
JBDEVSTUDIO_LINK=$JBDEVSTUDIO_DIR
JBDEVSTUDIO_INSTALADOR=jbdevstudio-product-eap-universal-7.1.1.GA-v20140314-2145-B688.jar

export JBDEVSTUDIO_HOME=$FERRAMENTAS_DIR/$JBDEVSTUDIO_DIR
export PATH=$JBDEVSTUDIO_HOME:$PATH
