JBOSS_LINK=jboss
JBOSS_VER=8.1.0.Final
JBOSS_DIR=wildfly-$JBOSS_VER
JBOSS_INSTALADOR=$JBOSS_DIR.tar.gz
JBOSS_INSTALADOR_URL_COMPLETA=http://download.jboss.org/wildfly/$JBOSS_VER/$JBOSS_INSTALADOR

export JBOSS_HOME=$FERRAMENTAS_DIR/jboss
export PATH=$JBOSS_HOME/bin:$PATH
